# TypeProf 0.21.3

# Classes
class Object
  private
  def fizz_buzz: (Integer num) -> String
end

class FizzBuzzTest
  def test_fizz_buzz: -> untyped
  def assert_equal: (untyped, untyped) -> void
end
